import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import NextProvider from "@/components/NextProvider";
import TopNav from "@/components/navbar/TopNav";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Match",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextProvider>
          <TopNav />
          <main className="container mx-auto">
            {children}
          </main>
        </NextProvider>
      </body>
    </html>
  );
}
